In [5]:
#Imports
import pandas as pd
import altair as alt
alt.__version__

'4.2.2'

## Drought Data
Obtained from: https://droughtmonitor.unl.edu/DmData/DataDownload/DSCI.aspx
- Selected states and calendar year 2016
- DSCI: Drought Severity and Coverage Index
Converts drought levels to a single value
Range is 0-500 with zero meaning none of the area is abnormally dry or in drought, a score of 500 means that all areas is in exceptional drought
- Recommendation is to average the value over a period of time if attempting to get a single value

In [6]:
drought_df = pd.read_csv('drought_monitor_export_20160101_20161231.csv')

In [8]:
drought_df['Name'].value_counts()

Alabama                 53
Alaska                  53
Nevada                  53
New Hampshire           53
New Jersey              53
New Mexico              53
New York                53
North Carolina          53
North Dakota            53
Ohio                    53
Oklahoma                53
Oregon                  53
Pennsylvania            53
Puerto Rico             53
Rhode Island            53
South Carolina          53
South Dakota            53
Tennessee               53
Texas                   53
Utah                    53
Vermont                 53
Virginia                53
Washington              53
West Virginia           53
Wisconsin               53
Nebraska                53
Montana                 53
Missouri                53
Idaho                   53
Arizona                 53
Arkansas                53
California              53
Colorado                53
Connecticut             53
Delaware                53
District of Columbia    53
Florida                 53
Georgia                 53
Hawaii                  53
Illinois                53
Mississippi             53
Indiana                 53
Iowa                    53
Kansas                  53
Kentucky                53
Louisiana               53
Maine                   53
Maryland                53
Massachusetts           53
Michigan                53
Minnesota               53
Wyoming                 53
Name: Name, dtype: int64

In [11]:
drought_df.shape

(2756, 3)

In [17]:
# Aggregate by state average
mean_state_drought = pd.DataFrame({'mean_DSCI': drought_df.groupby('Name')['DSCI'].mean().round(decimals = 2)}).reset_index()
mean_state_drought

                    Name  mean_DSCI
0                Alabama     124.70
1                 Alaska      12.87
2                Arizona     138.91
3               Arkansas      45.87
4             California     324.55
5               Colorado      38.28
6            Connecticut     170.83
7               Delaware       9.36
8   District of Columbia      34.89
9                Florida      19.70
10               Georgia     119.55
11                Hawaii      95.75
12                 Idaho      62.17
13              Illinois      10.02
14               Indiana      16.77
15                  Iowa      11.94
16                Kansas      30.13
17              Kentucky      49.62
18             Louisiana      51.49
19                 Maine      69.98
20              Maryland      26.15
21         Massachusetts     172.34
22              Michigan      15.32
23             Minnesota       8.15
24           Mississippi      97.42
25              Missouri      25.91
26               Montana      57.92
27              Nebraska      22.94
28                Nevada     166.58
29         New Hampshire     119.21
30            New Jersey      82.38
31            New Mexico      75.92
32              New York     105.58
33        North Carolina      40.51
34          North Dakota      32.79
35                  Ohio      32.08
36              Oklahoma      56.40
37                Oregon     133.68
38          Pennsylvania      58.83
39           Puerto Rico      41.40
40          Rhode Island     123.47
41        South Carolina      53.98
42          South Dakota      62.79
43             Tennessee     102.68
44                 Texas      21.19
45                  Utah      86.06
46               Vermont      88.38
47              Virginia      25.68
48            Washington      50.08
49         West Virginia      22.25
50             Wisconsin       1.45
51               Wyoming      67.58

In [35]:
#Bar chart of states: 
bars = alt.Chart(mean_state_drought, title= 'Mean Drought Severity by State for 2016: Zero = no drought, 500 = exceptional drought')\
.mark_bar().encode(
    x='mean_DSCI:Q',
    y= 'Name:O',
    color= alt.Color('mean_DSCI', legend=alt.Legend(title= 'Drought Severity'),\
                     scale=alt.Scale(scheme='turbo'))
)

text = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3  # Nudges text to right so it doesn't appear on top of the bar
).encode(
    text= 'mean_DSCI:Q'
)

(bars + text).properties(height=900)

alt.LayerChart(...)